GRANT SELECT, DELETE, INSERT, UPDATE ON SALES.DIM_PRODUCT                      TO GRIESMAYER;
GRANT SELECT, DELETE, INSERT, UPDATE ON SALES.DIM_SALES_CHANNEL                TO GRIESMAYER;
GRANT SELECT, DELETE, INSERT, UPDATE ON SALES.DIM_SALES_TIME                   TO GRIESMAYER;
GRANT SELECT, DELETE, INSERT, UPDATE ON SALES.DIM_SALES_TIME                   TO GRIESMAYER;
GRANT SELECT, DELETE, INSERT, UPDATE ON SALES.DIM_CUSTOMER                     TO GRIESMAYER;
GRANT SELECT, DELETE, INSERT, UPDATE ON SALES.FACT_GRIESMAYER_SALES_STAGING    TO GRIESMAYER;
GRANT SELECT, DELETE, INSERT, UPDATE ON SALES.FACT_GRIESMAYER_SALES            TO GRIESMAYER;
exit;

