DROP TABLESPACE TBS_GRIESMAYER_DWH INCLUDING CONTENTS AND DATAFILES;
DROP USER SALES CASCADE;
DROP USER GRIESMAYER CASCADE;



CREATE SMALLFILE TABLESPACE TBS_GRIESMAYER_DWH DATAFILE
'/home/oracle/app/oracle/oradata/orcl/griesmayer_dwh01.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
'/home/oracle/app/oracle/oradata/orcl/griesmayer_dwh02.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER GRIESMAYER PROFILE DEFAULT IDENTIFIED BY "oracle"
DEFAULT TABLESPACE TBS_GRIESMAYER_DWH
TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ANY DICTIONARY TO GRIESMAYER;
GRANT UNLIMITED TABLESPACE TO GRIESMAYER;
GRANT CONNECT TO GRIESMAYER;
GRANT RESOURCE TO GRIESMAYER;
GRANT CREATE TABLE TO GRIESMAYER;
GRANT CREATE ANY TABLE TO GRIESMAYER;
GRANT CREATE PROCEDURE TO GRIESMAYER;
GRANT CREATE ANY PROCEDURE TO GRIESMAYER;
GRANT EXECUTE ANY PROCEDURE TO GRIESMAYER;
GRANT CREATE SESSION TO GRIESMAYER;
GRANT SELECT ANY TABLE TO GRIESMAYER;



CREATE USER SALES PROFILE DEFAULT IDENTIFIED BY "oracle"
DEFAULT TABLESPACE TBS_GRIESMAYER_DWH
TEMPORARY TABLESPACE TEMP
ACCOUNT LOCK;
GRANT CREATE TABLE TO SALES;
GRANT UNLIMITED TABLESPACE TO SALES;

exit;


