DROP TABLESPACE TBS_MEIXNER_DWH INCLUDING CONTENTS AND DATAFILES;
DROP USER SALES CASCADE;
DROP USER MEIXNER CASCADE;

CREATE SMALLFILE TABLESPACE TBS_MEIXNER_DWH DATAFILE
'/home/oracle/app/oracle/oradata/orcl/meixner_dwh01.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
'/home/oracle/app/oracle/oradata/orcl/meixner_dwh02.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER MEIXNER PROFILE DEFAULT IDENTIFIED BY "oracle"
DEFAULT TABLESPACE TBS_MEIXNER_DWH
TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ANY DICTIONARY TO MEIXNER;
GRANT UNLIMITED TABLESPACE TO MEIXNER;
GRANT CONNECT TO MEIXNER;
GRANT RESOURCE TO MEIXNER;
GRANT CREATE TABLE TO MEIXNER;
GRANT CREATE ANY TABLE TO MEIXNER;
GRANT CREATE PROCEDURE TO MEIXNER;
GRANT CREATE ANY PROCEDURE TO MEIXNER;
GRANT EXECUTE ANY PROCEDURE TO MEIXNER;
GRANT CREATE SESSION TO MEIXNER;
GRANT SELECT ANY TABLE TO MEIXNER;



CREATE USER SALES PROFILE DEFAULT IDENTIFIED BY "oracle"
DEFAULT TABLESPACE TBS_MEIXNER_DWH
TEMPORARY TABLESPACE TEMP
ACCOUNT LOCK;
GRANT CREATE TABLE TO SALES;
GRANT UNLIMITED TABLESPACE TO SALES;

exit;


