GRANT SELECT, DELETE, INSERT, UPDATE ON DIM_PRODUCT                      TO MEIXNER;
GRANT SELECT, DELETE, INSERT, UPDATE ON DIM_SALES_CHANNEL                TO MEIXNER;
GRANT SELECT, DELETE, INSERT, UPDATE ON DIM_SALES_TIME                   TO MEIXNER;
GRANT SELECT, DELETE, INSERT, UPDATE ON DIM_SALES_TIME                   TO MEIXNER;
GRANT SELECT, DELETE, INSERT, UPDATE ON DIM_CUSTOMER                     TO MEIXNER;
GRANT SELECT, DELETE, INSERT, UPDATE ON FACT_MEIXNER_SALES_STAGING    TO MEIXNER;
GRANT SELECT, DELETE, INSERT, UPDATE ON FACT_MEIXNER_SALES            TO MEIXNER;
exit;

